### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LalitMaganti**

### CODE REVIEW

**Comment by rayhaanj** [comment]
Looks good!

**Comment by plietar** [comment]
:8ball:

**Comment by NorfairKing** [comment]
LGTM

**Comment by LalitMaganti** [comment]
@NakulK48 Please merge this pool request

**Comment by plietar** [comment]
+1

**Comment by LalitMaganti** [comment]
I'm disappointed this still hasn't been merged.

**Comment by NakulK48** [comment]
Do you have a test suite for this change?

**Pull request merged**
